# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymovies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_trailer', models.CharField(max_length=85)),
                ('movie_year', models.DateField()),
                ('movie_genre', models.CharField(choices=[('H', 'History'), ('Cl', 'Classic'), ('SF', 'Sci-Fi'), ('R', 'Romance'), ('A', 'Action'), ('Co', 'Comedy'), ('S', 'Supernatural')], max_length=200)),
                ('movie_description', models.TextField(blank=True)),
                ('movie_staff', models.CharField(max_length=500)),
                ('movie_image', models.ImageField(blank=True, upload_to='movie_imgs')),
                ('topic_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='yazar',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
