# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovies', '0004_auto_20171129_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(max_length=4),
        ),
    ]
