# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovies', '0005_auto_20171129_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_staff2',
            field=models.CharField(default='NONE', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(default=1996),
        ),
    ]
