# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovies', '0006_auto_20171129_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_tracks',
        ),
    ]
