# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovies', '0009_auto_20171129_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_super_hero',
            new_name='movie_super_heroes',
        ),
    ]
