# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovies', '0012_auto_20171130_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_imdb',
            field=models.FloatField(default=10),
        ),
    ]
