# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovies', '0013_movie_movie_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_tracks',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
